//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlahTune
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlahTuneEntities : DbContext
    {
        public SlahTuneEntities()
            : base("name=SlahTuneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artista> Artista { get; set; }
        public virtual DbSet<Musica> Musica { get; set; }
        public virtual DbSet<Nota> Nota { get; set; }
        public virtual DbSet<Tablatura> Tablatura { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
