//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlahTune
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nota
    {
        public int ID { get; set; }
        public string Nota1 { get; set; }
        public string Frequencia { get; set; }
    }
}
