//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlahTune
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablatura
    {
        public int ID { get; set; }
        public string Identificador { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public int IDMusica { get; set; }
    
        public virtual Musica Musica { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
